---
title: TMaize Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
encoding: utf-8
description: TMaize的个人博客
keywords: TMaize,Blog,Java,Html,JavaScript
author: TMaize
footerText: Copyright © 2016 皖ICP备16016174号
permalink: "/posts/:year/:month/:day/:title.html"
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude:
- CNAME
- README.md
- LICENSE
- _site
- dist
- Gemfile
- Gemfile.lock
- blog.sh
domainUrl: https://blog.tmaize.net
baseurl: ''
tucaoUrl: https://support.qq.com/product/86335
menu:
- title: 首页
  url: "/"
- title: 归类
  url: "/pages/categories.html"
- title: 搜索
  url: "/pages/search.html"
- title: 友链
  url: "/pages/links.html"
- title: 留言
  url: "/pages/chat.html"
- title: 关于
  url: "/pages/about.html"
extClickEffect: true
extAdsense: false
extMath: false
links:
- title: 文科中的技术宅
  url: https://www.townwang.com
- title: Auuu Nya Blog
  url: http://mu1er.cn
- title: 春风十里
  url: https://www.geek-era.com
- title: 阿川的个人博客
  url: https://achuan.io
- title: 魏文成博客
  url: https://www.wwc.ren
- title: 06m
  url: https://www.06m.me
- title: 达达知识
  url: https://www.dadapush.com
- title: 祈雨的博客
  url: https://wakzz.cn
- title: hongCYu’s Blog
  url: https://hongcyu.cn
- title: Sorryfu
  url: https://fushaolei.github.io
- title: 简单的人生笔记
  url: https://yoyling.com
- title: oneNeko的博客
  url: https://blog.oneneko.com
- title: Py's Whisper
  url: https://whisper.pyliubaolin.top
- title: Yuyao's Blog
  url: http://hellocode.ink
- title: 木叶的博客
  url: https://muye.ml
- title: Stansec
  url: https://standeblog.com
- title: Wenn的个人博客
  url: https://wenn.tech
